In [2]:
import pandas as pd

In [4]:
df=pd.read_csv('./food_data_final.csv')

In [5]:
df

,RCP_SNO,CKG_NM,CKG_MTRL_CN,rec1
0,128671,어묵김말이,[재료] 어묵 2개| 김밥용김 3장| 당면 1움큼| 양파 1/2개| 당근 1/2개|...,"['어묵', '김밥용김', '당면', '움큼', '양파', '당근', '깻잎', '..."
1,128892,두부새우전,[재료] 두부 1/2모| 당근 1/2개| 고추 2개| 브로콜리 1/4개| 새우 4마...,"['두부', '당근', '고추', '브로콜리', '새우', '녹말가루', '계란']"
2,128932,알밥,[재료] 밥 1+1/2공기| 당근 1/4개| 치자단무지 1/2개| 신김치 1쪽| 무...,"['밥', '당근', '치자단무지', '신김치', '무순', '날치알', '김가루'..."
3,131871,현미호두죽,[재료] 현미 4컵| 찹쌀 2컵| 호두 50g| 물 1/2컵| 소금 약간,"['현미', '찹쌀', '호두']"
4,139247,북어갈비,[재료] 북어포 1마리| 찹쌀가루 1C [양념] 간장 2T| 설탕 1T| 물 1T|...,"['북어포', '찹쌀가루', '파', '마늘']"
...,...,...,...,...
207494,7041366,도토리묵무침,[재료] 도토리묵700g| 상추10장(또는 쌈채소)| 당근1/2개|...,"['도토리묵', '상추', '쌈채소', '당근', '양파', '신김치', '마늘']"
207495,7041367,묵밥,[주재료] 도토리묵350g| 국물멸치1줌| 다시마1개| 물500...,"['도토리묵', '국물멸치', '다시마', '조미김', '청양고추', '김치양념장'..."
207496,7041368,세발나물무침,[재료] 세발나물200g| 소금0.5큰술(데칠용)| 국간장0.5큰술...,"['세발나물', '마늘']"
207497,7041369,제육볶음,[주재료] 대패삼겹살700g| 느타리버섯300g| 양파1/2개| 청...,"['대패삼겹살', '느타리버섯', '양파', '청양고추', '홍고추', '마늘', ..."
207498,7041370,애호박계란말이,[재료] 계란7개| 애호박1/4개| 당근1/5개| 쪽파3대(또...,"['계란', '애호박', '당근', '쪽파', '파', '부추']"

In [6]:
['recipe_id', 'food_name', 'ingred_view', 'ingred']

['recipe_id', 'food_name', 'ingred_view', 'ingred']

In [7]:
df.columns=['recipe_id', 'food_name', 'ingred_view', 'ingred']

In [8]:
df

,recipe_id,food_name,ingred_view,ingred
0,128671,어묵김말이,[재료] 어묵 2개| 김밥용김 3장| 당면 1움큼| 양파 1/2개| 당근 1/2개|...,"['어묵', '김밥용김', '당면', '움큼', '양파', '당근', '깻잎', '..."
1,128892,두부새우전,[재료] 두부 1/2모| 당근 1/2개| 고추 2개| 브로콜리 1/4개| 새우 4마...,"['두부', '당근', '고추', '브로콜리', '새우', '녹말가루', '계란']"
2,128932,알밥,[재료] 밥 1+1/2공기| 당근 1/4개| 치자단무지 1/2개| 신김치 1쪽| 무...,"['밥', '당근', '치자단무지', '신김치', '무순', '날치알', '김가루'..."
3,131871,현미호두죽,[재료] 현미 4컵| 찹쌀 2컵| 호두 50g| 물 1/2컵| 소금 약간,"['현미', '찹쌀', '호두']"
4,139247,북어갈비,[재료] 북어포 1마리| 찹쌀가루 1C [양념] 간장 2T| 설탕 1T| 물 1T|...,"['북어포', '찹쌀가루', '파', '마늘']"
...,...,...,...,...
207494,7041366,도토리묵무침,[재료] 도토리묵700g| 상추10장(또는 쌈채소)| 당근1/2개|...,"['도토리묵', '상추', '쌈채소', '당근', '양파', '신김치', '마늘']"
207495,7041367,묵밥,[주재료] 도토리묵350g| 국물멸치1줌| 다시마1개| 물500...,"['도토리묵', '국물멸치', '다시마', '조미김', '청양고추', '김치양념장'..."
207496,7041368,세발나물무침,[재료] 세발나물200g| 소금0.5큰술(데칠용)| 국간장0.5큰술...,"['세발나물', '마늘']"
207497,7041369,제육볶음,[주재료] 대패삼겹살700g| 느타리버섯300g| 양파1/2개| 청...,"['대패삼겹살', '느타리버섯', '양파', '청양고추', '홍고추', '마늘', ..."
207498,7041370,애호박계란말이,[재료] 계란7개| 애호박1/4개| 당근1/5개| 쪽파3대(또...,"['계란', '애호박', '당근', '쪽파', '파', '부추']"

In [11]:
df['ingred_view']=df['ingred_view'].str.replace("", " ", regex=True)

In [12]:
df['ingred_view']

0         [재료] 어묵 2개| 김밥용김 3장| 당면 1움큼| 양파 1/2개| 당근 1/2개|...
1         [재료] 두부 1/2모| 당근 1/2개| 고추 2개| 브로콜리 1/4개| 새우 4마...
2         [재료] 밥 1+1/2공기| 당근 1/4개| 치자단무지 1/2개| 신김치 1쪽| 무...
3                  [재료] 현미 4컵| 찹쌀 2컵| 호두 50g| 물 1/2컵| 소금 약간
4         [재료] 북어포 1마리| 찹쌀가루 1C [양념] 간장 2T| 설탕 1T| 물 1T|...
                                ...
207494    [재료] 도토리묵 700 g | 상추 10 장 (또는 쌈채소)| 당근 1/2 개 |...
207495    [주재료] 도토리묵 350 g | 국물멸치 1 줌 | 다시마 1 개 | 물 500 ...
207496    [재료] 세발나물 200 g | 소금 0.5 큰술 (데칠용)| 국간장 0.5 큰술 ...
207497    [주재료] 대패삼겹살 700 g | 느타리버섯 300 g | 양파 1/2 개 | 청...
207498    [재료] 계란 7 개 | 애호박 1/4 개 | 당근 1/5 개 | 쪽파 3 대 (또...
Name: ingred_view, Length: 207499, dtype: object

In [14]:
import re

# 모든 문자열을 하나로 합치기
all_text = ' '.join(df['ingred_view'].astype(str))

# 특수문자만 추출
special_chars = re.findall(r'[^a-zA-Z0-9가-힣\s]', all_text)
# 중복 제거 및 정렬
unique_special_chars = sorted(set(special_chars))

print(unique_special_chars)

['\x08', '!', '#', '%', '&', "'", '(', ')', '*', '+', '-', '.', '/', ':', ';', '<', '=', '>', '?', '@', '[', '\\', ']', '^', '_', '`', '{', '|', '}', '~', '±', '·', '¼', '½', '×', 'Ø', 'α', '\u200b', '–', '’', '…', '※', '\u2060', '℃', 'ℓ', '⅓', '⅔', '↑', '→', '①', '②', '③', 'ⓐ', 'ⓑ', 'ⓒ', '▲', '▶', '▼', '○', '★', '☆', '♡', '♣', '♥', '♧', '❗', '《', '》', '【', '】', 'ㄱ', 'ㄴ', 'ㄷ', 'ㄸ', 'ㄹ', 'ㅁ', 'ㅂ', 'ㅅ', 'ㅆ', 'ㅇ', 'ㅈ', 'ㅊ', 'ㅋ', 'ㅍ', 'ㅎ', 'ㅏ', 'ㅐ', 'ㅓ', 'ㅔ', 'ㅖ', 'ㅗ', 'ㅜ', 'ㅠ', 'ㅡ', 'ㅣ', 'ㆍ', '㎏', '㎖', '㎝', '中', '九', '入', '大', '小', '竟', '米', '驪', '️', '＋', '１', 'ｇ', '～']